server {
    listen 9050;
    server_name localhost;

    root /var/www/html/public;
    index index.php;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9050;  # PHP-FPM container on port 9050
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.(?!well-known).* {
        deny all;  # Deny access to hidden files
    }

    # Enable gzip compression for static files
    gzip on;
    gzip_types text/plain text/css application/javascript application/json application/xml application/xml+rss text/javascript;
    gzip_min_length 1000;
}
